#ifndef FLUID_LOG_H
#define FLUID_LOG_H

#include <QDebug>

#define FLUIDLOG_LEVEL_TRACE 0
#define FLUIDLOG_LEVEL_DEBUG 1
#define FLUIDLOG_LEVEL_INFO 2
#define FLUIDLOG_LEVEL_WARNING 3
#define FLUIDLOG_LEVEL_CRITICAL 4

#define FLUIDLOG_MIN_LEVEL FLUIDLOG_LEVEL_INFO

#define FLUIDLOG_NOTICE \
QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"\x1C""FLUID").debug

#define FLUIDLOG_TRACE \
    if(FLUIDLOG_MIN_LEVEL>FLUIDLOG_LEVEL_TRACE) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"\x1B""FLUID").debug
#define FLUIDLOG_DEBUG \
    if(FLUIDLOG_MIN_LEVEL>FLUIDLOG_LEVEL_DEBUG) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"FLUID").debug
#define FLUIDLOG_INFO \
    if(FLUIDLOG_MIN_LEVEL>FLUIDLOG_LEVEL_INFO) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"FLUID").info
#define FLUIDLOG_WARNING \
    if(FLUIDLOG_MIN_LEVEL>FLUIDLOG_LEVEL_WARNING) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"FLUID").warning
#define FLUIDLOG_CRITICAL \
    if(FLUIDLOG_MIN_LEVEL>FLUIDLOG_LEVEL_CRITICAL) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"FLUID").critical
#define FLUIDLOG_FATAL \
    QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"FLUID").fatal

#endif // FLUID_LOG_H
