#ifndef MEDIA_LOG_H
#define MEDIA_LOG_H

#include <QDebug>

#define MEDIALOG_LEVEL_TRACE 0
#define MEDIALOG_LEVEL_DEBUG 1
#define MEDIALOG_LEVEL_INFO 2
#define MEDIALOG_LEVEL_WARNING 3
#define MEDIALOG_LEVEL_CRITICAL 4

#define MEDIALOG_MIN_LEVEL MEDIALOG_LEVEL_INFO

#define MEDIALOG_NOTICE \
QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"\x1C""MEDIA").debug

#define MEDIALOG_TRACE \
    if(MEDIALOG_MIN_LEVEL>MEDIALOG_LEVEL_TRACE) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"\x1B""MEDIA").debug
#define MEDIALOG_DEBUG \
    if(MEDIALOG_MIN_LEVEL>MEDIALOG_LEVEL_DEBUG) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"MEDIA").debug
#define MEDIALOG_INFO \
    if(MEDIALOG_MIN_LEVEL>MEDIALOG_LEVEL_INFO) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"MEDIA").info
#define MEDIALOG_WARNING \
    if(MEDIALOG_MIN_LEVEL>MEDIALOG_LEVEL_WARNING) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"MEDIA").warning
#define MEDIALOG_CRITICAL \
    if(MEDIALOG_MIN_LEVEL>MEDIALOG_LEVEL_CRITICAL) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"MEDIA").critical
#define MEDIALOG_FATAL \
    QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"MEDIA").fatal

#endif // MEDIA_LOG_H
