#ifndef NETWORK_LOG_H
#define NETWORK_LOG_H

#include <QDebug>

#define NETWORKLOG_LEVEL_TRACE 0
#define NETWORKLOG_LEVEL_DEBUG 1
#define NETWORKLOG_LEVEL_INFO 2
#define NETWORKLOG_LEVEL_WARNING 3
#define NETWORKLOG_LEVEL_CRITICAL 4

#define NETWORKLOG_MIN_LEVEL NETWORKLOG_LEVEL_INFO

#define NETWORKLOG_NOTICE \
QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"\x1C""NETWORK").debug

#define NETWORKLOG_TRACE \
    if(NETWORKLOG_MIN_LEVEL>NETWORKLOG_LEVEL_TRACE) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"\x1B""NETWORK").debug
#define NETWORKLOG_DEBUG \
    if(NETWORKLOG_MIN_LEVEL>NETWORKLOG_LEVEL_DEBUG) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"NETWORK").debug
#define NETWORKLOG_INFO \
    if(NETWORKLOG_MIN_LEVEL>NETWORKLOG_LEVEL_INFO) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"NETWORK").info
#define NETWORKLOG_WARNING \
    if(NETWORKLOG_MIN_LEVEL>NETWORKLOG_LEVEL_WARNING) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"NETWORK").warning
#define NETWORKLOG_CRITICAL \
    if(NETWORKLOG_MIN_LEVEL>NETWORKLOG_LEVEL_CRITICAL) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"NETWORK").critical
#define NETWORKLOG_FATAL \
    QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"NETWORK").fatal

#endif // NETWORK_LOG_H
