#ifndef FSTAB_LOG_H
#define FSTAB_LOG_H

#include <QDebug>

#define FSTABLOG_LEVEL_TRACE 0
#define FSTABLOG_LEVEL_DEBUG 1
#define FSTABLOG_LEVEL_INFO 2
#define FSTABLOG_LEVEL_WARNING 3
#define FSTABLOG_LEVEL_CRITICAL 4

#define FSTABLOG_MIN_LEVEL FSTABLOG_LEVEL_INFO

#define FSTABLOG_NOTICE \
QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"\x1C""FSTAB").debug

#define FSTABLOG_TRACE \
    if(FSTABLOG_MIN_LEVEL>FSTABLOG_LEVEL_TRACE) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"\x1B""FSTAB").debug
#define FSTABLOG_DEBUG \
    if(FSTABLOG_MIN_LEVEL>FSTABLOG_LEVEL_DEBUG) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"FSTAB").debug
#define FSTABLOG_INFO \
    if(FSTABLOG_MIN_LEVEL>FSTABLOG_LEVEL_INFO) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"FSTAB").info
#define FSTABLOG_WARNING \
    if(FSTABLOG_MIN_LEVEL>FSTABLOG_LEVEL_WARNING) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"FSTAB").warning
#define FSTABLOG_CRITICAL \
    if(FSTABLOG_MIN_LEVEL>FSTABLOG_LEVEL_CRITICAL) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"FSTAB").critical
#define FSTABLOG_FATAL \
    QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"FSTAB").fatal

#endif // FSTAB_LOG_H
