#ifndef QPROJECTDEFS_H
#define QPROJECTDEFS_H

#include <QString>

#ifndef PROJECT_VERSION
#define PROJECT_VERSION ""
#endif

#ifndef PROJECT_VERSION_MAJOR
#define PROJECT_VERSION_MAJOR 0
#endif

#ifndef PROJECT_VERSION_MINOR
#define PROJECT_VERSION_MINOR 0
#endif

#ifndef PROJECT_VERSION_PATCH
#define PROJECT_VERSION_PATCH 0
#endif

#ifndef PROJECT_VERSION_SUFFIX
#define PROJECT_VERSION_SUFFIX ""
#endif

#ifndef PROJECT_VERSION_CODENAME
#define PROJECT_VERSION_CODENAME ""
#endif

#ifndef PROJECT_DESCRIPTION
#define PROJECT_DESCRIPTION ""
#endif

#ifndef PROJECT_NAME
#define PROJECT_NAME ""
#endif

#ifndef PROJECT_COMPANY
#define PROJECT_COMPANY ""
#endif

#ifndef PROJECT_COMPANY_ADDRESS
#define PROJECT_COMPANY_ADDRESS ""
#endif

#ifndef PROJECT_COMPANY_ZIPCODE
#define PROJECT_COMPANY_ZIPCODE ""
#endif

#ifndef PROJECT_COMPANY_CONTACT
#define PROJECT_COMPANY_CONTACT ""
#endif

#ifndef PROJECT_WEBSITE
#define PROJECT_WEBSITE ""
#endif

#ifndef PROJECT_DOMAIN
#define PROJECT_DOMAIN ""
#endif

#ifndef PROJECT_COPYRIGHT
#define PROJECT_COPYRIGHT ""
#endif

#ifndef PROJECT_MAINTAINER
#define PROJECT_MAINTAINER ""
#endif

#endif // QPROJECTDEFS_H
