function(target_try_link_libraries TARGET LIBRARY PREFIX)

    set(args_single HEADER PACKAGE PACKAGE_TARGET)
    set(args_multi NAMES)
    cmake_parse_arguments(PARSE_ARGV 3 arg "" "${args_single}" "${args_multi}")

    if(NOT arg_NAMES)
        set(arg_NAMES ${LIBRARY})
    endif()

    if(arg_PACKAGE AND arg_PACKAGE_TARGET)
        find_package(${arg_PACKAGE} CONFIG QUIET)
        if(TARGET ${arg_PACKAGE_TARGET})
            message(NOTICE "${arg_PACKAGE} package found. Building with ${PREFIX} support.")
            target_link_libraries(${TARGET} PRIVATE ${arg_PACKAGE_TARGET})
            target_compile_definitions(${TARGET} PRIVATE ${PREFIX}_FOUND)
            return()
        endif()
    endif()

    set(${PREFIX}_FOUND FALSE)
    find_package(PkgConfig QUIET)
    if(PkgConfig_FOUND)
        pkg_check_modules(${PREFIX} QUIET IMPORTED_TARGET ${LIBRARY})
    endif()

    if(${PREFIX}_FOUND AND arg_HEADER)
        find_path(${PREFIX}_INCLUDE_DIR
            NAMES ${arg_HEADER}
            HINTS ${${PREFIX}_INCLUDE_DIRS})
        if(NOT ${PREFIX}_INCLUDE_DIR)
            message(NOTICE "${LIBRARY} found without ${arg_HEADER}. Building ${TARGET} without ${PREFIX} support.")
            set(${PREFIX}_FOUND FALSE)
        endif()
    endif()

    if(${PREFIX}_FOUND)
        message(NOTICE "${LIBRARY} version ${${PREFIX}_VERSION} found. Building with ${PREFIX} support.")
        target_link_libraries(${TARGET} PRIVATE PkgConfig::${PREFIX})
        if(arg_HEADER)
            target_include_directories(${TARGET} PRIVATE ${${PREFIX}_INCLUDE_DIR})
        endif()
        target_compile_definitions(${TARGET} PRIVATE ${PREFIX}_FOUND)
    else()
        find_library(${PREFIX}_LIB NAMES ${arg_NAMES})
        set(_required_header_found TRUE)
        if(arg_HEADER)
            find_path(${PREFIX}_INCLUDE_DIR NAMES ${arg_HEADER})
            if(NOT ${PREFIX}_INCLUDE_DIR)
                set(_required_header_found FALSE)
            endif()
        endif()

        if(${PREFIX}_LIB AND _required_header_found)
            message(NOTICE "${LIBRARY} found. Building with ${PREFIX} support.")
            target_link_libraries(${TARGET} PRIVATE ${${PREFIX}_LIB})
            if(arg_HEADER)
                target_include_directories(${TARGET} PRIVATE ${${PREFIX}_INCLUDE_DIR})
            endif()
            target_compile_definitions(${TARGET} PRIVATE ${PREFIX}_FOUND)
        else()
            message(NOTICE "${LIBRARY} not found. Building ${TARGET} without ${PREFIX} support.")
        endif()
    endif()

endfunction()
