#ifndef HASS_LOG_H
#define HASS_LOG_H

#include <QDebug>

#define HASSLOG_LEVEL_TRACE 0
#define HASSLOG_LEVEL_DEBUG 1
#define HASSLOG_LEVEL_INFO 2
#define HASSLOG_LEVEL_WARNING 3
#define HASSLOG_LEVEL_CRITICAL 4

#define HASSLOG_MIN_LEVEL HASSLOG_LEVEL_INFO

#define HASSLOG_NOTICE \
QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"\x1C""HASS").debug

#define HASSLOG_TRACE \
    if(HASSLOG_MIN_LEVEL>HASSLOG_LEVEL_TRACE) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"\x1B""HASS").debug
#define HASSLOG_DEBUG \
    if(HASSLOG_MIN_LEVEL>HASSLOG_LEVEL_DEBUG) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"HASS").debug
#define HASSLOG_INFO \
    if(HASSLOG_MIN_LEVEL>HASSLOG_LEVEL_INFO) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"HASS").info
#define HASSLOG_WARNING \
    if(HASSLOG_MIN_LEVEL>HASSLOG_LEVEL_WARNING) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"HASS").warning
#define HASSLOG_CRITICAL \
    if(HASSLOG_MIN_LEVEL>HASSLOG_LEVEL_CRITICAL) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"HASS").critical
#define HASSLOG_FATAL \
    QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"HASS").fatal

#endif // HASS_LOG_H
